"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { labels, stages, kinds, closed, dateLabel, todayDenver, totals, money, type Workspace, type RecordItem, type Invoice, type Task, type Kind } from "@/lib/crm/model";
import { loadWorkspace, saveRecord, saveInvoice, saveTask } from "./crm-actions";
import styles from "./crm.module.css";
import WinningScorecard from "./WinningScorecard";
const emptyRecord = (kind:Kind): RecordItem => ({ id:"",kind,organization:"",title:"",contact:"",email:"",stage:stages[kind][0],value:null,event_date:null,next_action:"",next_action_due:null,notes:"",source:"Stephen",needs_review:false,updated_at:"" });
const tabs = ["Overview","Clients","Outreach","Speaking & workshops","Invoices","Work queue","Activity"];
type Editor = { type:"record"; value:RecordItem } | { type:"invoice"; value:Invoice } | {type:"task";value:Task};
export default function CrmWorkspace({ initial, preview=false, loadError }: { initial: Workspace; preview?:boolean; loadError?:string }) {
  const [data,setData]=useState(initial),[tab,setTab]=useState("Overview"),[query,setQuery]=useState(""),[showHistory,setShowHistory]=useState(false);
  const [editor,setEditor]=useState<Editor|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(loadError||""),[sync,setSync]=useState(preview?"Local preview":"Connecting"),[lastSync,setLastSync]=useState("");
  const [ready,setReady]=useState(!loadError);
  const dialog=useRef<HTMLDialogElement>(null),refreshBusy=useRef(false);
  const today=todayDenver(),summary=totals(data);
  useEffect(()=> { if(editor) dialog.current?.showModal(); else dialog.current?.close(); },[editor]);
  useEffect(()=> {
    if(preview) return;
    let active=true,connected=false;
    const refresh=async()=> {
      if(refreshBusy.current) return; refreshBusy.current=true;
      try { const next=await loadWorkspace(); if(active){setData(next);setReady(true);setSync(connected?"Live updates connected":"Checking every 30 seconds");setLastSync(new Date().toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"}));} }
      catch { if(active) setSync("Connection interrupted · retrying"); }
      finally {refreshBusy.current=false;}
    };
    const db=createClient(),channel=db.channel("crm-workspace");
    for(const table of ["crm_records","crm_invoices","crm_tasks","crm_activity","crm_goals","crm_other_income"]) channel.on("postgres_changes",{event:"*",schema:"public",table},()=>void refresh());
    channel.subscribe(status=> {connected=status==="SUBSCRIBED";if(active)setSync(connected?"Live updates connected":"Checking every 30 seconds");if(connected)void refresh();});
    const timer=setInterval(()=>void refresh(),30000);
    const onVisible=()=> {if(document.visibilityState==="visible")void refresh();};
    document.addEventListener("visibilitychange",onVisible);
    return()=>{active=false;clearInterval(timer);document.removeEventListener("visibilitychange",onVisible);void db.removeChannel(channel);};
  },[preview]);
  async function persist(e:React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); if(!editor)return;
    if(preview){setNotice("Preview only. Changes are not saved to your CRM.");return;}
    setBusy(true);setNotice("");
    try {const value=editor.value;const next=editor.type==="record"?await saveRecord({...value}):editor.type==="invoice"?await saveInvoice({...value}):await saveTask({...value});setData(next);setEditor(null);setNotice("Saved to your CRM.");}
    catch(error){setNotice(error instanceof Error?error.message:"Could not save. Please try again.");}finally{setBusy(false);}
  }
  async function toggleTask(task:Task){if(preview){setNotice("Preview only. Tasks are not changed.");return;}setBusy(true);try{setData(await saveTask({...task,done:!task.done}));setNotice(task.done?"Task reopened.":"Task completed.");}catch(e){setNotice(e instanceof Error?e.message:"Could not save task.");}finally{setBusy(false);}}
  async function refresh(){setBusy(true);try{setData(await loadWorkspace());setReady(true);setNotice("CRM refreshed.");}catch(e){setNotice(e instanceof Error?e.message:"Could not refresh.");}finally{setBusy(false);}}
  function field(key:string,value:unknown){setEditor(current=>current?{...current,value:{...current.value,[key]:value}} as Editor:null);}
  function addInvoice(){setEditor({type:"invoice",value:{id:"",record_id:data.records.find(r=>r.kind==="client")?.id||"",label:"",amount:0,status:"draft",issued_on:today,due_on:null,paid_on:null,notes:"",updated_at:""}});}
  function addTask(){setEditor({type:"task",value:{id:"",record_id:null,title:"",due_on:null,done:false,updated_at:""}});}
  const matches=(r:RecordItem)=>`${r.organization} ${r.contact} ${r.title} ${r.email}`.toLowerCase().includes(query.toLowerCase());
  const attention=data.records.filter(r=>!closed(r)&&(r.needs_review||(r.next_action_due&&r.next_action_due<=today)||r.stage==="conversation"));
  const clientRows=data.records.filter(r=>r.kind==="client"&&!closed(r)),dueTasks=data.tasks.filter(t=>!t.done);
  const displayRecords=data.records.filter(r=>matches(r)&&(showHistory||!closed(r))&&(tab==="Clients"?r.kind==="client":tab==="Outreach"?r.kind==="consulting":r.kind==="speaking"||r.kind==="workshop"));
  const card=(r:RecordItem)=><button key={r.id} className={styles.recordCard} onClick={()=>setEditor({type:"record",value:r})}>
    <div className={styles.cardTop}><span className={`${styles.pill} ${["active","conversation","booked"].includes(r.stage)?styles.green:r.stage==="declined"?styles.muted:""}`}>{r.stage==="scouted"&&r.kind==="consulting"?"Scouted · not contacted":labels[r.stage]}</span>{r.needs_review&&<span className={styles.review}>Verify status</span>}</div>
    <h3>{r.organization}</h3><p>{r.title}</p>{r.contact&&<p className={styles.contact}>{r.contact}</p>}
    <div className={styles.next}><span>Next move</span><p>{r.next_action||"No next action set"}</p>{r.next_action_due&&<small>{dateLabel(r.next_action_due)}</small>}</div>
    <div className={styles.cardFoot}><span>{labels[r.kind]}</span><span>{r.value!==null?money(Number(r.value)):r.event_date?dateLabel(r.event_date):"Open record →"}</span></div>
  </button>;
  return <div className={styles.workspace}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Foundations & Horizons / Private workspace</p><h1>Your business, in motion.</h1><p>Build strong client systems. Keep good conversations moving.</p></div><div className={styles.headerActions}><span className={styles.sync}><i/>{sync}{lastSync?` · checked ${lastSync}`:""}</span><button className={styles.primary} disabled={!ready} onClick={()=>setEditor({type:"record",value:emptyRecord("consulting")})}>＋ Add relationship</button></div></header>
    {preview&&<div className={styles.banner}>Design preview · dated business context, with saving disabled. The private CRM uses your live database.</div>}
    {notice&&<div role="status" className={styles.banner}>{notice}<button aria-label="Dismiss message" onClick={()=>setNotice("")}>×</button></div>}
    <nav aria-label="CRM sections" className={styles.tabs}>{tabs.map(t=><button key={t} aria-current={tab===t?"page":undefined} className={tab===t?styles.activeTab:""} onClick={()=>{setTab(t);setQuery("");}}>{t}</button>)}</nav>
    {tab==="Overview"?<>
      {ready&&<WinningScorecard data={data} preview={preview} onUpdate={setData}/>}
      <section className={styles.stats} aria-label="Business totals">{[["Active clients",summary.clients],["Contracted work",money(summary.contracted)],["Invoiced · awaiting payment",money(summary.receivable)],["Speaking applications",summary.applied]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
      <div className={styles.overviewGrid}><section className={styles.panel}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Client delivery</p><h2>The work you’ve won.</h2></div><button onClick={()=>setTab("Clients")}>View clients →</button></div>
        {clientRows.length?clientRows.map(r=><div key={r.id} className={styles.feature}><div><span className={`${styles.pill} ${styles.green}`}>{labels[r.stage]}</span><h3>{r.organization}</h3><p>{r.title} · {r.contact}</p></div><div className={styles.featureFacts}><div><span>Project fee</span><strong>{money(Number(r.value||0))}</strong></div><div><span>Kickoff / key date</span><strong>{dateLabel(r.event_date)}</strong></div></div><p className={styles.featureNote}>{r.next_action}</p><button className={styles.secondary} onClick={()=>setEditor({type:"record",value:r})}>Open project →</button></div>):<p className={styles.empty}>No active clients yet. Add a client when work is agreed.</p>}
      </section><section className={styles.panel}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Your next moves</p><h2>Needs your attention.</h2></div><span className={styles.count}>{attention.length+dueTasks.length}</span></div>
        {dueTasks.slice(0,4).map(t=><div className={styles.attention} key={t.id}><button className={styles.check} disabled={busy} aria-label={`Complete ${t.title}`} onClick={()=>void toggleTask(t)}>✓</button><div><strong>{t.title}</strong><small>{dateLabel(t.due_on)}</small></div></div>)}
        {attention.slice(0,4).map(r=><button key={r.id} className={styles.attention} onClick={()=>setEditor({type:"record",value:r})}><div><strong>{r.organization}</strong><p>{r.next_action||"Verify the latest status"}</p><small>{r.needs_review?"Latest status needs verification":dateLabel(r.next_action_due)}</small></div><span>↗</span></button>)}
        {!attention.length&&!dueTasks.length&&<p className={styles.empty}>Nothing waiting on you.</p>}
      </section></div>
      <section className={styles.panel}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Relationship pipeline</p><h2>From a good fit to a real conversation.</h2></div><button onClick={()=>setTab("Outreach")}>View outreach →</button></div><div className={styles.pipeline}>{["scouted","contacted","replied","conversation","proposal"].map(stage=><button key={stage} onClick={()=>setTab("Outreach")}><span>{stage==="scouted"?"Scouted":labels[stage]}</span><strong>{data.records.filter(r=>r.kind==="consulting"&&r.stage===stage).length}</strong></button>)}</div></section>
      <div className={styles.bottomNote}>Scouting is research. Applied means submitted. Invoiced means sent. Paid means payment confirmed.</div>
    </>:null}
    {["Clients","Outreach","Speaking & workshops"].includes(tab)?<>
      <div className={styles.toolbar}><div><h2>{tab==="Clients"?"Delivery, milestones & handoff":tab==="Outreach"?"Consulting relationships":"Speaking & workshops"}</h2><p>{tab==="Speaking & workshops"?`${summary.applied} active applications · scout finds stay separate from submitted proposals.`:tab==="Outreach"?"Small nonprofit teams. Real operational signals. Thoughtful outreach.":"Track the work after a proposal becomes a client."}</p></div><button className={styles.primary} disabled={!ready} onClick={()=>setEditor({type:"record",value:emptyRecord(tab==="Clients"?"client":tab==="Outreach"?"consulting":"speaking")})}>＋ Add {tab==="Clients"?"client":tab==="Outreach"?"prospect":"opportunity"}</button></div>
      <div className={styles.filters}><input aria-label="Search relationships" placeholder="Search organization, person or email…" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={showHistory} onChange={e=>setShowHistory(e.target.checked)}/> Include closed & paused</label></div>
      <div className={styles.cards}>{displayRecords.map(card)}</div>{!displayRecords.length&&<p className={styles.empty}>No matching records.</p>}
    </>:null}
    {tab==="Invoices"?<><div className={styles.toolbar}><div><h2>Invoices & cash received</h2><p>Track invoices already issued. Sending and payment confirmation happen separately.</p></div><button className={styles.primary} disabled={!data.records.length||!ready} onClick={addInvoice}>＋ Log invoice</button></div><section className={styles.stats}>{[["Awaiting payment",money(summary.receivable)],["Payment confirmed",money(summary.paid)],["Draft invoices",data.invoices.filter(i=>i.status==="draft").length]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</section><div className={styles.tableWrap}><table><thead><tr><th>Client / invoice</th><th>Amount</th><th>Status</th><th>Issued</th><th>Due</th><th>Paid</th><th/></tr></thead><tbody>{data.invoices.map(i=><tr key={i.id}><td><strong>{data.records.find(r=>r.id===i.record_id)?.organization}</strong><small>{i.label}</small></td><td>{money(Number(i.amount))}</td><td><span className={styles.pill}>{i.status}</span></td><td>{dateLabel(i.issued_on)}</td><td>{dateLabel(i.due_on)}</td><td>{i.paid_on?dateLabel(i.paid_on):"Not confirmed"}</td><td><button onClick={()=>setEditor({type:"invoice",value:i})}>Edit</button></td></tr>)}</tbody></table>{!data.invoices.length&&<p className={styles.empty}>No invoices logged.</p>}</div></>:null}
    {tab==="Work queue"?<><div className={styles.toolbar}><div><h2>Milestones & follow-ups</h2><p>One next move at a time.</p></div><button className={styles.primary} disabled={!ready} onClick={addTask}>＋ Add task</button></div><section className={styles.panel}>{data.tasks.map(t=><div className={styles.attention} key={t.id}><button className={`${styles.check} ${t.done?styles.done:""}`} disabled={busy} aria-label={`${t.done?"Reopen":"Complete"} ${t.title}`} onClick={()=>void toggleTask(t)}>{t.done?"✓":""}</button><button className={styles.taskBody} onClick={()=>setEditor({type:"task",value:t})}><strong style={{textDecoration:t.done?"line-through":"none"}}>{t.title}</strong><small>{data.records.find(r=>r.id===t.record_id)?.organization||"Business"} · {dateLabel(t.due_on)}</small></button></div>)}{!data.tasks.length&&<p className={styles.empty}>No tasks yet.</p>}</section></>:null}
    {tab==="Activity"?<><div className={styles.toolbar}><div><h2>What happened, and where it came from.</h2><p>Confirmed events from your scouts, Reply Watch and manual updates.</p></div><button className={styles.secondary} disabled={preview||busy} onClick={()=>void refresh()}>Refresh now</button></div><section className={styles.panel}>{data.activity.map(a=><div className={styles.activity} key={a.id}><span className={styles.pill}>{a.event_type.replaceAll("_"," ")}</span><div><strong>{data.records.find(r=>r.id===a.record_id)?.organization||"Business"}</strong><p>{a.summary}</p><small>{a.source.replaceAll("_"," ")} · {new Date(a.occurred_at).toLocaleString("en-US",{timeZone:"America/Denver"})}</small></div></div>)}{!data.activity.length&&<p className={styles.empty}>No events logged yet. Your connected scouts will add confirmed activity here.</p>}</section></>:null}
    <footer className={styles.footer}><span>Systems, not heroics.</span><div><Link href="/dashboard/scout-inbox">Scout Inbox</Link><Link href="/dashboard/deals">Earlier CRM records</Link><Link href="/dashboard/inquiries">Website inquiries</Link><Link href="/dashboard/linkedin">Visibility</Link><Link href="/dashboard/books">Book sales</Link><Link href="/dashboard/finance">Expenses & accounting</Link></div></footer>
    <dialog ref={dialog} className={styles.dialog} onCancel={e=>{if(busy)e.preventDefault();else setEditor(null);}}><form onSubmit={persist}>
      <div className={styles.dialogHeader}><h2>{editor?.value.id?"Edit":"Add"} {editor?.type==="record"?"relationship":editor?.type}</h2><button type="button" aria-label="Close editor" disabled={busy} onClick={()=>setEditor(null)}>×</button></div>
      {editor?.type==="record"?<div className={styles.formGrid}>
        <label>Area<select value={editor.value.kind} onChange={e=>{field("kind",e.target.value);field("stage",stages[e.target.value as Kind][0]);}}>{kinds.map(k=><option value={k} key={k}>{labels[k]}</option>)}</select></label><label>Status<select value={editor.value.stage} onChange={e=>field("stage",e.target.value)}>{stages[editor.value.kind].map(s=><option key={s} value={s}>{s==="scouted"&&editor.value.kind==="consulting"?"Scouted · not contacted":labels[s]}</option>)}</select></label>
        <label>Organization<input required maxLength={250} value={editor.value.organization} onChange={e=>field("organization",e.target.value)}/></label><label>Project / opportunity<input required maxLength={250} value={editor.value.title} onChange={e=>field("title",e.target.value)}/></label><label>Contact<input value={editor.value.contact} onChange={e=>field("contact",e.target.value)}/></label><label>Email<input type="email" value={editor.value.email} onChange={e=>field("email",e.target.value)}/></label>
        <label>Agreed / estimated value<input type="number" min="0" step="0.01" value={editor.value.value??""} onChange={e=>field("value",e.target.value===""?null:Number(e.target.value))}/></label><label>Kickoff / event date<input type="date" value={editor.value.event_date||""} onChange={e=>field("event_date",e.target.value||null)}/></label><label>Next action<input value={editor.value.next_action} onChange={e=>field("next_action",e.target.value)}/></label><label>Next action date<input type="date" value={editor.value.next_action_due||""} onChange={e=>field("next_action_due",e.target.value||null)}/></label>
        <label className={styles.full}>Notes / scope<textarea rows={5} value={editor.value.notes} onChange={e=>field("notes",e.target.value)}/></label><label className={styles.full}>Source / evidence<input value={editor.value.source} onChange={e=>field("source",e.target.value)}/></label><label className={styles.checkbox}><input type="checkbox" checked={editor.value.needs_review} onChange={e=>field("needs_review",e.target.checked)}/> Latest status needs verification</label>
      </div>:null}
      {editor?.type==="invoice"?<div className={styles.formGrid}><label className={styles.full}>Client / relationship<select required value={editor.value.record_id} onChange={e=>field("record_id",e.target.value)}><option value="">Choose a record</option>{data.records.map(r=><option value={r.id} key={r.id}>{r.organization} · {r.title}</option>)}</select></label><label>Invoice label<input required value={editor.value.label} onChange={e=>field("label",e.target.value)}/></label><label>Square invoice number<input placeholder="Optional · e.g. 000002" value={editor.value.import_key?.replace(/^square:/,"")||""} onChange={e=>field("import_key",e.target.value?`square:${e.target.value}`:null)}/></label><label>Amount<input required type="number" min="0" step="0.01" value={editor.value.amount} onChange={e=>field("amount",Number(e.target.value))}/></label><label>Status<select value={editor.value.status} onChange={e=>{field("status",e.target.value);if(e.target.value!=="paid")field("paid_on",null);}}>{["draft","sent","paid","void"].map(s=><option key={s}>{s}</option>)}</select></label><label>Issued date<input type="date" value={editor.value.issued_on||""} onChange={e=>field("issued_on",e.target.value||null)}/></label><label>Due date<input type="date" value={editor.value.due_on||""} onChange={e=>field("due_on",e.target.value||null)}/></label><label>Payment received date<input type="date" required={editor.value.status==="paid"} disabled={editor.value.status!=="paid"} value={editor.value.paid_on||""} onChange={e=>field("paid_on",e.target.value||null)}/></label><label className={styles.full}>Notes<textarea rows={3} value={editor.value.notes} onChange={e=>field("notes",e.target.value)}/></label></div>:null}
      {editor?.type==="task"?<div className={styles.formGrid}><label className={styles.full}>Task<input required value={editor.value.title} onChange={e=>field("title",e.target.value)}/></label><label>Linked relationship<select value={editor.value.record_id||""} onChange={e=>field("record_id",e.target.value||null)}><option value="">Business</option>{data.records.map(r=><option key={r.id} value={r.id}>{r.organization}</option>)}</select></label><label>Due date<input type="date" value={editor.value.due_on||""} onChange={e=>field("due_on",e.target.value||null)}/></label><label className={styles.checkbox}><input type="checkbox" checked={editor.value.done} onChange={e=>field("done",e.target.checked)}/> Completed</label></div>:null}
      {notice&&<p role="status" className={styles.formNotice}>{notice}</p>}<div className={styles.dialogFoot}><button className={styles.secondary} type="button" disabled={busy} onClick={()=>setEditor(null)}>Cancel</button><button className={styles.primary} disabled={busy||preview||!ready} type="submit">{busy?"Saving…":preview?"Preview · saving disabled":"Save changes"}</button></div>
    </form></dialog>
  </div>;
}

