"use client";
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {loadInbox,reviewFinding} from './actions';
import type {InboxData,InboxStatus,ScoutFinding} from './model';
const statuses:InboxStatus[]=['New','Pursue','Hold','Pass'];
const stamp=(s:string)=>new Date(s).toLocaleString('en-US',{timeZone:'America/Denver'});
const safeUrl=(s:string)=>/^https?:\/\//i.test(s)?s:undefined;
export default function ScoutInbox({initial,loadError}:{initial:InboxData;loadError?:string}){
 const dialog=useRef<HTMLDialogElement>(null);
 const [data,setData]=useState(initial),[filter,setFilter]=useState<InboxStatus|'All'>('New'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(!loadError),[notice,setNotice]=useState(loadError||''),[selected,setSelected]=useState<ScoutFinding|null>(null),[kind,setKind]=useState('consulting'),[entity,setEntity]=useState(''),[notes,setNotes]=useState(''),[after,setAfter]=useState('');
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
 useEffect(()=>{let active=true;const timer=setInterval(()=>{void loadInbox().then(next=>{if(active){setData(next);setReady(true);}}).catch(()=>{if(active){setReady(false);setNotice('Connection interrupted. Refresh before reviewing.');}});},30000);return()=>{active=false;clearInterval(timer);};},[]);
 async function refresh(){setBusy(true);try{setData(await loadInbox());setReady(true);setNotice('Inbox refreshed.');}catch(e){setReady(false);setNotice(e instanceof Error?e.message:'Could not refresh.');}finally{setBusy(false);}}
 function open(item:ScoutFinding){setSelected(item);setKind(item.crm_kind||'consulting');setEntity('');setNotes(item.review_notes);setAfter(item.review_after||'');}
 async function decide(status:InboxStatus){if(!selected||busy||!ready)return;setBusy(true);try{setData(await reviewFinding({id:selected.id,status,kind,entity_key:entity,notes,review_after:status==='Hold'?after:null,updated_at:selected.updated_at}));setSelected(null);setNotice(status==='Pursue'?'Pursue saved and linked to the CRM.':`${status} saved. Finding remains in the inbox.`);}catch(e){setNotice(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 const shown=data.items.filter(i=>(filter==='All'||i.status===filter)&&`${i.organization} ${i.title} ${i.scout} ${i.category}`.toLowerCase().includes(query.toLowerCase()));
 const button='rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold disabled:opacity-40 hover:bg-slate-50';
 return <div className="text-[#10213f]">
  <header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Foundations & Horizons / Command Center</p><h1 className="mt-2 font-serif text-4xl">Scout Inbox</h1><p className="mt-3 max-w-2xl text-slate-600">Good findings first. Stephen and Chief of Staff decide the next move. Only Pursue adds an opportunity to the CRM.</p></div><div className="flex gap-2"><Link className={button} href="/dashboard">Back to CRM</Link><button className={button} disabled={busy} onClick={()=>void refresh()}>Refresh</button></div></header>
  {notice&&<p role="status" className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4">{notice}</p>}
  <nav aria-label="Inbox status" className="mb-4 flex flex-wrap gap-2">{[...statuses,'All' as const].map(s=><button key={s} className={`${button} ${s===filter?'bg-[#10213f] text-white hover:bg-[#10213f]':''}`} aria-pressed={s===filter} onClick={()=>setFilter(s)}>{s} · {data.items.filter(i=>s==='All'||i.status===s).length}</button>)}</nav>
  <input className="mb-5 w-full rounded-xl border border-slate-200 bg-white p-3" aria-label="Search scout findings" placeholder="Search organization, opportunity, scout…" value={query} onChange={e=>setQuery(e.target.value)}/>
  <div className="grid gap-4 lg:grid-cols-2">{shown.map(i=><article key={i.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-3 flex flex-wrap justify-between gap-2 text-xs"><span className="rounded-full bg-slate-100 px-3 py-1 font-bold">{i.status}</span><span className="text-slate-500">{i.scout} · {i.category}</span></div><h2 className="font-serif text-2xl">{i.organization}</h2><p className="mt-1 font-semibold">{i.title}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{i.fit_reason}</p>{i.deadline_at&&<p className="mt-3 text-sm font-semibold text-amber-800">Deadline: {stamp(i.deadline_at)}</p>}{i.review_after&&<p className="mt-2 text-sm">Review after: {i.review_after}</p>}<div className="mt-4 flex flex-wrap items-center justify-between gap-3"><small className="text-slate-500">Found {stamp(i.discovered_at)} · {i.seen_count} sighting{i.seen_count===1?'':'s'}</small><button className={button} disabled={!ready||busy} onClick={()=>open(i)}>Review finding</button></div>{i.crm_record_id&&<p className="mt-3 text-xs text-emerald-700">Linked to CRM · review history retained</p>}</article>)}</div>
  {!shown.length&&<div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-500">{ready?'No findings in this view. New scout findings will arrive here for your morning review.':'Inbox unavailable. Refresh to reconnect.'}</div>}
  <dialog ref={dialog} aria-labelledby="finding-title" className="m-auto max-h-[90vh] w-[calc(100%-2rem)] max-w-3xl overflow-y-auto rounded-2xl border-0 bg-white p-5 text-[#10213f] shadow-xl backdrop:bg-slate-950/50 sm:p-8" onCancel={e=>{if(busy)e.preventDefault();else setSelected(null);}}>{selected&&<div><div className="flex justify-between gap-4"><h2 id="finding-title" className="font-serif text-3xl">{selected.organization}</h2><button className={button} disabled={busy} onClick={()=>setSelected(null)}>Close</button></div><p className="mt-2 font-semibold">{selected.title} · {selected.opportunity_type}</p>
   <dl className="my-6 space-y-4 text-sm">{[['Why it fits',selected.fit_reason],['Recommendation',selected.recommendation],['Scout notes',selected.notes],['Last decision',`${selected.status} · ${selected.review_notes||'No review notes'}`]].map(([label,value])=><div key={label}><dt className="font-bold">{label}</dt><dd className="mt-1 whitespace-pre-wrap leading-6 text-slate-600">{value||'Not provided'}</dd></div>)}<div><dt className="font-bold">Contact · {selected.email_verified?'email verified by scout':'verification needed'}</dt><dd className="mt-1 whitespace-pre-wrap break-words">{JSON.stringify(selected.contact,null,2)}</dd></div><div><dt className="font-bold">Important dates</dt><dd className="mt-1 whitespace-pre-wrap">{JSON.stringify(selected.important_dates,null,2)}</dd></div><div><dt className="font-bold">Source</dt><dd className="mt-1 break-all"><a href={safeUrl(selected.source_url)} target="_blank" rel="noopener noreferrer" className="underline">{selected.source_url}</a></dd></div></dl>
   {!selected.crm_record_id&&<div className="mb-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">CRM category for Pursue<select className="mt-2 w-full rounded-xl border p-3" value={kind} onChange={e=>{setKind(e.target.value);setEntity('');}}>{['consulting','speaking','workshop','client'].map(k=><option key={k}>{k}</option>)}</select></label><label className="text-sm font-semibold">Link existing opportunity (optional)<select className="mt-2 w-full rounded-xl border p-3" value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Automatic deduplication</option>{data.records.filter(r=>r.kind===kind&&r.entity_key).map(r=><option key={r.id} value={r.entity_key!}>{r.organization} · {r.title}</option>)}</select></label></div>}
   <label className="block text-sm font-semibold">Review notes<textarea className="mt-2 w-full rounded-xl border p-3" rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="mt-4 block text-sm font-semibold">Review again after (for Hold)<input className="ml-3 rounded-xl border p-2" type="date" value={after} onChange={e=>setAfter(e.target.value)}/></label>
   <details className="my-5 text-sm"><summary className="cursor-pointer font-semibold">Original finding and dedupe key</summary><p className="my-2 break-all">{selected.dedupe_key}</p><pre className="max-h-64 overflow-auto rounded-xl bg-slate-50 p-3 whitespace-pre-wrap break-words">{JSON.stringify(selected.original_finding,null,2)}</pre></details>
   {notice&&<p role="status" className="my-3 text-sm text-amber-800">{notice}</p>}<div className="flex flex-wrap gap-3">{statuses.map(s=><button key={s} disabled={busy||!ready} className={`${button} ${s==='Pursue'?'bg-emerald-700 text-white hover:bg-emerald-800':''}`} onClick={()=>void decide(s)}>{busy?'Saving…':s==='New'?'Return to New':s}</button>)}</div><p className="mt-4 text-xs text-slate-500">Hold and Pass never delete a finding. Changing a previously pursued finding does not remove its CRM record.</p>
  </div>}</dialog>
 </div>;
}
